// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIrDRtpLUqvoFe076bxBlUnr5wGkgeriQ',
    appId: '1:765931589519:web:f8ff042f522b59e7d8c5fa',
    messagingSenderId: '765931589519',
    projectId: 'sense-stm',
    authDomain: 'sense-stm.firebaseapp.com',
    storageBucket: 'sense-stm.appspot.com',
    measurementId: 'G-M52Q8WWK4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSs2MyJ2A21O6xaMjnNCRlr1fSx3LBMoQ',
    appId: '1:765931589519:android:d1baa04a3742ee06d8c5fa',
    messagingSenderId: '765931589519',
    projectId: 'sense-stm',
    storageBucket: 'sense-stm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO7Oy62nDwKZCEoXrPpIKsBam5tzj7wVw',
    appId: '1:765931589519:ios:d8a6d4b821ffdbb1d8c5fa',
    messagingSenderId: '765931589519',
    projectId: 'sense-stm',
    storageBucket: 'sense-stm.appspot.com',
    iosBundleId: 'com.example.senseStm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO7Oy62nDwKZCEoXrPpIKsBam5tzj7wVw',
    appId: '1:765931589519:ios:d8a6d4b821ffdbb1d8c5fa',
    messagingSenderId: '765931589519',
    projectId: 'sense-stm',
    storageBucket: 'sense-stm.appspot.com',
    iosBundleId: 'com.example.senseStm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIrDRtpLUqvoFe076bxBlUnr5wGkgeriQ',
    appId: '1:765931589519:web:5541158620898f91d8c5fa',
    messagingSenderId: '765931589519',
    projectId: 'sense-stm',
    authDomain: 'sense-stm.firebaseapp.com',
    storageBucket: 'sense-stm.appspot.com',
    measurementId: 'G-8ZWD4XNV1N',
  );
}
